"use client";

import { craftingStyles } from "galadrielcss";
import { useSelector } from "react-redux";
import Markdown from "react-markdown";
// Importing the CSS file generated by Galadriel.CSS
import "./page.css";
import GaladrielCard from "@/components/card/GaladrielCard";

export default function Home() {
    const mainStyles = craftingStyles(() => ({
        background: "transparent",
        display: "$panel-flex",
        gap: "6%",
        flexDirection: "column",
        justifyContent: "$organize-content-start",
        alignItems: "$adjust-center",
        overflow: "$excess-hidden",
        height: "100%",
        width: "100%",
    }));

    const titleContainer = craftingStyles(() => ({
        backgroundImage:
            "linear-gradient(to right top, #f16e22, #f06228, #ed552d, #eb4733, #e73838)",
        border: "1px solid rgba(0,0,0,0.4)",
        borderRadius: "8px",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
        height: "6%",
        width: "80%",
    }));

    const titleStyles = craftingStyles(() => ({
        fontSize: "16px",
        fontWeight: "bold",
    }));

    const content = craftingStyles(() => ({
        display: "flex",
        gap: "10px",
        flexDirection: "column",
        justifyContent: "start",
        alignItems: "start",
        paddingBottom: "0px",
        height: "88%",
        width: "100%",
        overflow: "hidden",
        overflowY: "auto",
    }));

    const { title, data } = useSelector((state: any) => state.home.content.content);

    return (
        <div className={mainStyles}>
            <div className={titleContainer}>
                <span className={titleStyles}>{title}</span>
            </div>
            <div className={content}>
                <Markdown>{data}</Markdown>
                <GaladrielCard />
            </div>
        </div>
    );
}